import { Amplify } from 'aws-amplify';
import outputs from '@/amplify_outputs.json';

/**
 * Configures Amplify using the auto-generated amplify_outputs.json.
 * Generated by `npx ampx sandbox` (local dev) or `npx ampx pipeline-deploy` (staging/prod).
 * Committed to the repo so Vercel builds can read it without extra env vars.
 */
export function configureAmplify() {
  Amplify.configure(outputs, { ssr: true });
}
